Fix chunk <-> block confusion providing comments to explain what is what
gfx-rs/gfx-memory pull request #6
Opened 2018-02-15 12:01 UTC by omni-viral

2018-02-15 15:31 UTC, kvark commented on src/chunked.rs
> +/// Chunks is super-allocator block
"Chunks is"

2018-02-15 15:31 UTC, kvark commented on src/chunked.rs
> +/// That is devided into smaller blocks
as this starts with capital letter, we need to end the previous sentence with a period.

2018-02-15 15:31 UTC, kvark commented on src/chunked.rs
> +        // Push into free blocks list
not sure if omitting all the prepositions is good here, spreading "a"/"the" before used terms may make the comments more readable and add a bit of semantics

2018-02-17 00:25 UTC, mjadczak requested changes
I agree with @kvark that the clarity of the wording could be a little improved—I went through and suggested the wording to use in each case.

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +/// Chunks is super-allocator block
> Chunks are super-allocator blocks, which are then divided into smaller 'blocks'

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Blocks count is chunk count multiplyed by blocks per chunk
multiplyed -> multiplied

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // How much blocks there in chunk
This comment is probably redundant given the function name, but should be
> How many blocks there are in a chunk

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Get new chunk
> Get a new chunk

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // It takes next index
> `len()` will return the next index to use

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Fill free list with new blocks
> Fill the free list with new blocks

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Put new chunk in list
> Place the new chunk in the list

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Find free block
> Find a free block

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +            // Remember what chunk it came from
> Remember what chunk the block came from

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Try to allocate block
> Try to allocate a block

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Confirm chunk index
> Confirm the chunk index

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Calculate block index inside chunk
> Calculate the block index inside the chunk

2018-02-17 00:25 UTC, mjadczak commented on src/chunked.rs
> +        // Push into free blocks list
> Push the block back into the 'free blocks' list

2018-02-17 13:19 UTC, kvark approved these changes
nice, thanks!
bors r+

2018-02-17 13:21 UTC, merged